give @p dragonmounts:aether_dragon_egg 64
give @p dragonmounts:enchant_dragon_egg 64
give @p dragonmounts:ender_dragon_egg 64
give @p dragonmounts:fire_dragon_egg 64
give @p dragonmounts:forest_dragon_egg 64 
give @p dragonmounts:ice_dragon_egg 64 
give @p dragonmounts:moonlight_dragon_egg 64 
give @p dragonmounts:nether_dragon_egg 64 
give @p dragonmounts:skeleton_dragon_egg 64 
give @p dragonmounts:storm_dragon_egg 64 
give @p dragonmounts:sunlight_dragon_egg 64 
give @p dragonmounts:terra_dragon_egg 64 
give @p dragonmounts:water_dragon_egg 64 
give @p dragonmounts:wither_dragon_egg 64 
give @p dragonmounts:zombie_dragon_egg 64