tag @e remove aether_1
tag @e remove aether_2
tag @e remove aether_3
tag @e remove aether_4
tag @e remove enchant_1
tag @e remove enchant_2
tag @e remove enchant_3
tag @e remove enchant_4
tag @e remove ender_1
tag @e remove ender_2
tag @e remove ender_3
tag @e remove ender_4
tag @e remove fire_1
tag @e remove fire_2
tag @e remove fire_3
tag @e remove fire_4
tag @e remove forest_1
tag @e remove forest_2
tag @e remove forest_3
tag @e remove forest_4
tag @e remove ice_1
tag @e remove ice_2
tag @e remove ice_3
tag @e remove ice_4
tag @e remove moonlight_1
tag @e remove moonlight_2
tag @e remove moonlight_3
tag @e remove moonlight_4
tag @e remove nether_1
tag @e remove nether_2
tag @e remove nether_3
tag @e remove nether_4
tag @e remove sculk_1
tag @e remove sculk_2
tag @e remove sculk_3
tag @e remove sculk_4
tag @e remove storm_1
tag @e remove storm_2
tag @e remove storm_3
tag @e remove storm_4
tag @e remove sunlight_1
tag @e remove sunlight_2
tag @e remove sunlight_3
tag @e remove sunlight_4
tag @e remove terra_1
tag @e remove terra_2
tag @e remove terra_3
tag @e remove terra_4
tag @e remove water_1
tag @e remove water_2
tag @e remove water_3
tag @e remove water_4
tag @e remove zombie_1
tag @e remove zombie_2
tag @e remove zombie_3
tag @e remove zombie_4